/**
 * Bindings are generated by `wrangler types` into worker-configuration.d.ts as
 * `Cloudflare.Env` - never hand-write them, they drift from wrangler.toml.
 * Re-run `wrangler types` after adding or renaming a binding.
 *
 * Secrets are not part of the generated bindings (they are not in the config
 * file), so BOOTSTRAP_CODE is declared here explicitly.
 */
export interface Env extends Cloudflare.Env {
  /** One-time code a browser presents to obtain a device token. Secret. */
  BOOTSTRAP_CODE: string;
}
