-- One row per calendar date. Written only by garmin_sync.py (scope 'ingest');
-- the browser only ever pulls this domain, never writes it — see domains.ts.
CREATE TABLE garmin_daily (
  id                          TEXT PRIMARY KEY,
  revision                    INTEGER NOT NULL,
  updated_at                  TEXT NOT NULL,
  deleted_at                  TEXT,
  source                      TEXT,
  steps                       REAL,
  step_goal                   REAL,
  distance_km                 REAL,
  total_calories               REAL,
  active_calories              REAL,
  bmr_calories                 REAL,
  rhr                          REAL,
  min_heart_rate                REAL,
  max_heart_rate                REAL,
  hrv                          REAL,
  hrv_weekly_avg                 REAL,
  hrv_status                    TEXT,
  sleep_hours                   REAL,
  sleep_score                   REAL,
  deep_sleep_hours                REAL,
  light_sleep_hours               REAL,
  rem_sleep_hours                REAL,
  awake_sleep_hours               REAL,
  average_sleep_stress              REAL,
  average_stress                 REAL,
  stress_qualifier                TEXT,
  body_battery_wake                REAL,
  body_battery_high                REAL,
  body_battery_low                 REAL,
  body_battery_latest               REAL,
  body_battery_charged              REAL,
  body_battery_drained               REAL,
  average_spo2                  REAL,
  lowest_spo2                   REAL,
  average_respiration               REAL,
  moderate_intensity_minutes           REAL,
  vigorous_intensity_minutes           REAL,
  floors_ascended                 REAL,
  sedentary_hours                 REAL,
  active_hours                  REAL,
  garmin_details                 TEXT
);
CREATE INDEX idx_garmin_daily_revision ON garmin_daily (revision);
